### ISSUE TITLE
Unable to start a new job after stopping a previous one

### ISSUE THREAD

**Issue by uniederer** [Snapmaker/Snapmaker2-Controller#64]
With Snapmaker 2, Firmware V1.10.1_20200822, i run regularly into the situation, where a print job is started, but temperatures are set to 0 after a few seconds. (G code is generated by either Luban v3.12.3 or v3.13.1)

Steps to reproduce:

1. Start a 3D printing job
2. During heat up phase (and I believe also during print) hit "Stop"
3. As soon as the UI allows for starting a new print, start any other print
4. Observe the temperatures:
   a.  The new set points are according to the new part
   b. After a couple of seconds, the set points drop to 0, the controller remains in "heatup" mode.

The only way to persuade SM2 to start another print I've seen so far is to powercycle the whole machine.

Does anybody else have this issue as well?

**Comment by daniel-starke** [comment]
Same issue on my side. Also with G-code generated by PrusaSlicer.

**Comment by scotthsl** [comment]
Thanks for your feedback!

Based on your description, that should be a known issue. When you don't start heating the nozzle from room temperature, it may trigger a heating failure. That's because the V1.10.1 firmware's thermal protection is too sensitive, and next release will fix that. The temporary solution for now is to wait until the temperature of the nozzle drops to room temperature before starting to heat it up again.

**Comment by uniederer** [comment]
@daniel-starke Oops... didin't notice that one. Thanks for linking. It looks indeed related.
@scotthsl After upgrading to the latest firmware just released lately, it appears indeed, that the issue is gone. I'll do some extra testing again and then report back.

**Comment by scotthsl** [comment]
Hi Uniederer,
If this issue reappears, please provide log of the console output about the nozzle heating.

To record the logs:
You could connect the machine to luban's console, or other console tool, and then keep the console open to reproduce the issue.

Thanks a lot!
Scott
