### ISSUE TITLE
Feature request: Enable powerdown while pausing

### ISSUE THREAD

**Issue by Letme** [Snapmaker/Snapmaker2-Controller#97]
When you pause the job it stops printing, but most of us are bothered by the loud fan in the power supply unit, so I would like to turn power supply off and resume printing once it is powered back on. There is an issue open for this in Luban (https://github.com/Snapmaker/Luban/issues/790), but I feel this is more fitting. Since there is high request for this on forums (https://forum.snapmaker.com/t/pause-and-resume-via-luban/9291 https://forum.snapmaker.com/t/can-i-pause-and-restart-3d-printing/6763) I think this would be a valuable addition.

What I now do is pull the power plug and then let automatic recovery do the job. It might drag the last layer and cause a mess and hardware/software also probably does not like it when you just hardcore plug off the power. So lets make this graceful and provide an option to Pause and power down, which would save position of nozzle, heated, temperatures and position in gcode before performing a powerdown. That would then enable resume on poweron same as it does with recovery, except with a lot more details saved.

As mentioned, I am willing to donate some coffee to a developer implementing this as it would help me a lot.

**Comment by ldp7** [comment]
@Letme 

Thank you for reporting this issue.

You can turn off the switch in the back of the power unit directly and the Power-loss feature will be triggered.
![image](https://user-images.githubusercontent.com/62584712/114494094-4ab9ba00-9c4e-11eb-8281-0de23fb7713c.png)

If you shut down the machine, it does not have enough power to move the printing module to the HOME position. I think this may ruin some prints because the nozzle is still hot.

My suggestion is that you can pause the machine and then shut it. When you resume the work, the nozzle will not ruin the models.

I do hope this can help you.

Cheers 
Edwin

**Comment by xhycode** [comment]
I will close this issue, if you have the same problem you can open it again.

**Comment by 70853n** [comment]
Forward to 2025, the controllers fan is still (annoyingly) loud at 50 db. Hence pausing and turning off the machine seems to be a valueable feature, as many customers are asking for. The only way to shut down the machine is to switch off the power supply unit. But the controller only shuts off with a delay. Is there an internal procedure that persists the currents state, so resuming the work is no problem later?
